### ISSUE TITLE
Add option to override the name of an attached file

### ISSUE THREAD

**Issue by betterphp** [chobie/jira-api-restclient#141]
It would be useful to be able to set the name of a file that is uploaded manually instead of relying on the path.

We have a form that people use to create issues in JIRA and to implement the file upload we have to move the file to a temp location with it's real name before submitting to JIRA. I'd like to be able to do this without having to move the file.

I can do a PR for this but wanted to get an opinion first.

**Comment by aik099** [comment]
Sure, why not. Right now we're already creating attachment name as `basename($filename)`. We can have extra optional parameter called `$name` and when empty fallback to current code.

**Comment by DerMika** [comment]
I could use such a feature as well.

**Comment by betterphp** [comment]
`public function createAttachment($issue_key, $filename, array $options = array())`
What's the purpose of `$options` in this method? It doesn't look like there is anything other than `$data['file']` that gets used. I'm just thinking it would be nicer to have a named parameter instead of using the generic options array?

**Comment by aik099** [comment]
This `$options` parameter looks like a mistake to me, because https://docs.atlassian.com/jira/REST/cloud/#api/2/issue/{issueIdOrKey}/attachments REST call doesn't accept any options. Since BC breaks are allowed we can safely:

1. replace `$options` parameter with `$name = null` parameter (in the method itself we still use `$options` variable as before)
2. specify `$name` parameter value in the `name` key of `$options` variable
3. in the client classes use `name` parameter as filename
4. add corresponding client class tests
