### ISSUE TITLE
Add "scope" as an acceptable key to prevent IssueType throwing exception

### ISSUE THREAD

**Issue by danillofb** [chobie/jira-api-restclient#182]
Some time ago JIRA API was changed and now `scope` is returned as part of `issuetype` properties in the list of returned issues (see https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-api-2-issueLink-linkId-get).

Since it's not explicitly whitelisted in `\chobie\Jira\ IssueType::$_acceptableKeys` property the exception is thrown during API response parsing.

Closed by #181.

**Comment by aik099** [comment]
Some things needs fixing, before associated PR can be merged:

1. The PR is merely implementation of topic, discussed in the issue. Since PR come and go, but issue itself stays, then it must have proper description and not other way around.
2. The title of an issue is not very descriptive. I know (from our prior communication), that you want to support scopes of an issues type entity, but issue title itself doesn't even partially resemble that. Also no need for a trailing dot, because issue/pr title isn't a sentence :)
